### PR TITLE
Added JEP-200 exclusions for use when monitoring agents

### PR DESCRIPTION
**Pull request by jglick**
See https://github.com/jenkinsci/jenkins/pull/3120.

@reviewbybees

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
have you tested that? There is a risk that there are some nested types.

**Comment by evernat** [comment]
Thanks for the PR.
I have 2 questions:
1. All objects serialized by the plugin are in the whitelist of this PR or are basic classes already in the Jenkins whitelist, except java.lang.Thread$State. Is it necessary to add java.lang.Thread$State to this PR and to https://github.com/jenkinsci/jenkins/pull/3120 ? (It's a simple enum).

2. Before 1.68.0 of the monitoring plugin, the same 11 classes were in the net.bull.javamelody package and not in the net.bull.javamelody.internal.model package. According to [stats](http://stats.jenkins.io/plugin-installation-trend/monitoring.stats.json), about 5000 installations are 1.68+ and ok with the current whitelist, so about 6000 installations are not. Perhaps those 6000 installations will not upgrade to the latest Jenkins without upgrading the plugin, but we don't know that. So for those 6000 installations to work with the latest Jenkins, should the same 11 classes be added with the net.bull.javamelody package in the whitelists of the two PR?

**Comment by jglick** [comment]
> have you tested that?

Yes, I ran `mock-slave` and tried to use all the plugin features I could find on a mock agent until I fixed all the errors.

> All objects serialized by the plugin are in the whitelist of this PR or are basic classes already in the Jenkins whitelist

See JEP-200 for details. I believe this PR is all that is needed.

> So for those 6000 installations to work with the latest Jenkins, should the same 11 classes be added

You should release this PR and people should just upgrade their plugin if they expect things to work. Anyway if you [look at the correlation](http://stats.jenkins.io/pluginversions/monitoring.html) you will see that the vast majority of people who have updated Jenkins to a weekly release are also using the latest release of this plugin—there are only a handful of people who updated Jenkins but declined to update the plugin. That is the normal situation for most plugins.

**Comment by evernat** [comment]
Tested ok.
This will be released in the [monitoring plugin](https://wiki.jenkins.io/display/JENKINS/Monitoring) 1.71.0 certainly in a few days.

**Comment by oleg-nenashev** [comment]
Apparently the core's patch works only for 1.68 or above (https://github.com/jenkinsci/monitoring-plugin/commit/5cb1c662058b89830e45f30b7207796fb2090f80). I will add the plugin to https://wiki.jenkins.io/display/JENKINS/Plugins+affected+by+fix+for+JEP-200

**Comment by oleg-nenashev** [comment]
Created https://issues.jenkins-ci.org/browse/JENKINS-50280 as a placeholder

**Pull request merged**
