### PR TITLE
Test with Java 21

### PR DESCRIPTION
**Pull request by MarkEWaite**
## Test with Java 21

Java 21 was released Sep 19, 2023. We want to announce full support for Java 21 in early October and would like the most used plugins to be compiled and tested with Java 21.

The acceptance test harness and plugin bill of materials tests are already passing with Java 21. This is a further step to improve plugin readiness for use with Java 21 and for development with Java 21.

The change intentionally tests only two Java configurations, Java 17 and Java 21 because we believe that the risk of a regression that only affects Java 11 is low. We generate Java 11 byte code with the Java 17 and the Java 21 builds, so we're already testing Java 11 byte code.

Includes the pull request:

* #11

### Testing done

Confirmed that tests pass with Java 21 on Linux.

### Submitter checklist
- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes

### CODE REVIEW

**Comment by andham** [comment]
To my understanding, this will also avoid implied dependencies in Jenkins as described in PR #8, which would be awesome!
Can this be merged and released please?

**Comment by MarkEWaite** [comment]
@andham thanks for asking.  Would you be interested in [adopting the plugin](https://www.jenkins.io/doc/developer/plugin-governance/adopt-a-plugin/) so that you could merge the change and release a new version?

**Comment by MarkEWaite** [comment]
@evernat or @kohsuke would you be willing to merge this pull request so that the plugin is regularly tested with Java 21?  No need for a release, just a merge of the change.

**Comment by kohsuke** [comment]
Not that I work on this plugin, but I didn't want to waste the good effort from @MarkEWaite so I went ahead and pressed the button.

**Comment by MarkEWaite** [comment]
@andham an [incremental build](https://repo.jenkins-ci.org/incrementals/org/jvnet/hudson/plugins/monitoring/1.95.0-rc525.72de5a_b_70b_a_d/monitoring-1.95.0-rc525.72de5a_b_70b_a_d.hpi) of the plugin with this change is available.  Could you test it and share the results so that others know if it resolves the question you asked earlier in https://github.com/jenkinsci/monitoring-plugin/pull/12#issuecomment-1779084050 ?

**Comment by andham** [comment]
I've tested the linked incremental build on Jenkins 2.414.3 on openJDK 11 and I can confirm it avoids the implied dependencies.

**Comment by evernat** [comment]
Thanks @andham and @MarkEWaite 
Note that this plugin is not abandoned and I continue to maintain it, like I did for the last 14 years. Version is synchronized by me with javamelody-core and release is automated with a script which is not here.

PR #11 was on hold following very unpleasant discussion about itext dependency in particular. 
I think I am not resentful, so we can put that under the carpet.

**Comment by MarkEWaite** [comment]
> Thanks @andham and @MarkEWaite Note that this plugin is not abandoned and I continue to maintain it, like I have done for the last 14 years. Version is synchronized by me with javamelody-core and release is automated with a script which is not here.

Thanks very much for maintaining the plugin!  Much appreciated.  I wasn't aware that the version number is synchronized with the release of javamelody-core.  Considering the multiple plugins that you maintain for java-melody core, that makes sense.  It also makes sense that the release script is outside this repository, since there are plugins for multiple systems (Jenkins, Confluence, Bamboo, ...).

**Pull request merged**
